import * as functions from "firebase-functions";
import express from "express";
import cors from "cors";
import matrixRouter from "./routes/matrixRouter";
import approvedRulesRouter from "./routes/approvedRulesRouter";
const app = express();
app.use(cors());
app.use(express.json());
app.use("/matrix", matrixRouter);
app.use("/approved", approvedRulesRouter);
export const api = functions.https.onRequest(app);
